### ISSUE TITLE
IllegalStateException FragmentViewBindingProperty.getLifecycleOwner

### ISSUE THREAD

**Issue by galaxi76** [androidbroadcast/ViewBindingPropertyDelegate#105]
Fragment doesn't have view associated with it or the view has been destroyed

by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getLifecycleOwner (FragmentViewBindings.kt:65)
by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getLifecycleOwner (FragmentViewBindings.kt:34)
by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue (ViewBindingProperty.kt:76)
by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue (FragmentViewBindings.kt:42)
by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue (FragmentViewBindings.kt:34)
com.xxx.MainFragment.getBinding (MainFragment.kt:53)
com.xxx.MainFragment.onSaveInstanceState (MainFragment.kt:216)

90% occurrence in background

**Comment by kirich1409** [comment]
This is normal behaviour, because Fragment's view has been destroyed.
Try to add check
```kotlin
if (view != null) {
   // Do something with viewBinding
}
```
