### ISSUE TITLE
UnresolvedReference

### ISSUE THREAD

**Issue by KAZTIIL** [androidbroadcast/ViewBindingPropertyDelegate#106]
When using the viewBinding in Activity I get the following error
![IMAGE 2022-10-19 12:20:14](https://user-images.githubusercontent.com/116158920/196651247-aefef431-42b3-43fd-9ad7-d469be0873e6.jpg)

**Comment by kirich1409** [comment]
Did you use the latest version? Check dependencies and imports. Very strange issue

**Comment by kirich1409** [comment]
No info. Close it
