### ISSUE TITLE
Generic type cannot be used

### ISSUE THREAD

**Issue by merlinJeyakumar** [androidbroadcast/ViewBindingPropertyDelegate#117]
How to use generic type

abstract class BaseActivity<B : ViewDataBinding, VM : BaseViewModel>(
    private val bindingFactory: Int,
    private val viewModelClass: Class<VM>,
) : AppCompatActivity() {

protected val binding: B by viewBinding()

}

**Comment by kirich1409** [comment]
It's not possible. To create an instance the delegate needs to now ViewBinding class.

**Comment by kirich1409** [comment]
The delegate few creation variants and one of them has ViewModel class as parameter or even you can pass function where you will create an instance of ViewBinding

**Comment by kirich1409** [comment]
https://github.com/androidbroadcast/ViewBindingPropertyDelegate/blob/master/vbpd/vbpd-full/src/main/java/by/kirich1409/viewbindingdelegate/ActivityViewBindings.kt
 37 line

**Comment by merlinJeyakumar** [comment]
class ContentViewBindingDelegate<in R : AppCompatActivity, out T : ViewDataBinding>(
    @LayoutRes private val layoutRes: Int,
) {

    private var binding: T? = null

    operator fun getValue(activity: R, property: KProperty<*>): T {
        if (binding == null) {
            binding = DataBindingUtil.setContentView<T>(activity, layoutRes).apply {
                lifecycleOwner = activity
            }
        }
        return binding!!
    }
}

fun <R : AppCompatActivity, T : ViewDataBinding> contentView(
    @LayoutRes layoutRes: Int,
): ContentViewBindingDelegate<R, T> = ContentViewBindingDelegate(layoutRes)



I have created and using this extension function, while using it with navigation view it causing crash NavHost.context() null pointer

**Comment by merlinJeyakumar** [comment]
its working fine for my [baseclass](https://github.com/merlinJeyakumar/jeyksupport/blob/main/src/main/java/com/nativedevps/support/base_class/BaseActivity.kt),

you can close this ticket, Problem is I called lifecycle binding before activity creation
