### ISSUE TITLE
Is it possible to provide support for viewBinding(ViewBinding::inflate)

### ISSUE THREAD

**Issue by weijia1991** [androidbroadcast/ViewBindingPropertyDelegate#120]
In a custom view, I would like to use viewBingding like below:
```kotlin
class ProfileView(context: Context) : LinearLayout(context) {
    
    private val viewBinding by viewBinding(ViewProfileBinding::inflate)
}
```

**Comment by achatina** [comment]
Is it so necessary for you? Just use ViewProfileBinding.inflate(LayoutInflater.from(context), this) 

This lib was created for simplyfing work with lifecycle of viewBinding entities and soon as your view don't need to watch when fragment\activity died - you don't need it.

**Comment by weijia1991** [comment]
I get. Thanks
