### ISSUE TITLE
你好在1.5.0-beta01中使用出现问题，在1.4.7中没有问题

### ISSUE THREAD

**Issue by lhj1079947827** [androidbroadcast/ViewBindingPropertyDelegate#76]
我在Activity中初始化viewbinding和根据反射创建view但是Activity的onCreate中使用报如下错误！
[
![image](https://user-images.githubusercontent.com/20966610/131477161-51003a43-994d-478d-ab29-019f88da22c3.png)
](url)
在activity中使用viewbinding如下：
[
![image](https://user-images.githubusercontent.com/20966610/131477453-dd786370-c313-4206-8d34-dc368da50831.png)
](url)

**Comment by kirich1409** [comment]
I don't understand the issue
