### ISSUE TITLE
java.lang.IllegalStateException: Host view isn't ready to create a ViedBinding instance

### ISSUE THREAD

**Issue by mochadwi** [androidbroadcast/ViewBindingPropertyDelegate#78]
When calling the activity from deeplink, the `viewBinding` has a runtime crashed

`java.lang.IllegalStateException: Host view isn't ready to create a ViedBinding instance` does the ViewBindingPropertyDelegate not currently supported if accessing the activity through deeplink?

**Comment by kirich1409** [comment]
You tried to access to the viewbidning before Activity/Fragment/ViewGroup has content
