### ISSUE TITLE
Host view isn't ready to create a ViewBinding instance

### ISSUE THREAD

**Issue by DATL4G** [androidbroadcast/ViewBindingPropertyDelegate#93]
I'm facing an issue with the latest version (1.5.3) where ```Host view isn't ready to create a ViewBinding instance``` occurs.

Full Stacktrace: 
```bash
java.lang.IllegalStateException: Host view isn't ready to create a ViewBinding instance
        at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:87)
        at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:61)
        at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:51)
        at de.datlag.burningseries.ui.fragment.ScrapeHosterFragment.getBinding(ScrapeHosterFragment.kt:34)
        at de.datlag.burningseries.ui.fragment.ScrapeHosterFragment.access$getBinding(ScrapeHosterFragment.kt:29)
        at de.datlag.burningseries.ui.fragment.ScrapeHosterFragment$saveStream$1$1.invokeSuspend(ScrapeHosterFragment.kt:92)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8030)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

I'm able to reproduce this consistently [BurningSeries-Android](https://github.com/DATL4G/BurningSeries-Android) inside the [SeriesFragment](https://github.com/DATL4G/BurningSeries-Android/blob/master/app/src/main/java/de/datlag/burningseries/ui/fragment/SeriesFragment.kt).
The normal way I navigate there is from [HomeFragment](https://github.com/DATL4G/BurningSeries-Android/blob/master/app/src/main/java/de/datlag/burningseries/ui/fragment/HomeFragment.kt#L127) and this works fine, however when I navigate to the [VideoFragment](https://github.com/DATL4G/BurningSeries-Android/blob/master/app/src/main/java/de/datlag/burningseries/ui/fragment/VideoFragment.kt) from there and then to the [ScrapeHosterFragment](https://github.com/DATL4G/BurningSeries-Android/blob/master/app/src/main/java/de/datlag/burningseries/ui/fragment/ScrapeHosterFragment.kt) and after that to the [SaveScrapedDialog](https://github.com/DATL4G/BurningSeries-Android/blob/master/app/src/main/java/de/datlag/burningseries/ui/dialog/SaveScrapedDialog.kt) lastly back to the SeriesFragment the app crashes because of this error.

It's maybe hard to understand but basicly the navigation hierarchy looks like this:

[HomeFragment](https://github.com/DATL4G/BurningSeries-Android/blob/master/app/src/main/java/de/datlag/burningseries/ui/fragment/HomeFragment.kt#L127) -> [SeriesFragment](https://github.com/DATL4G/BurningSeries-Android/blob/master/app/src/main/java/de/datlag/burningseries/ui/fragment/SeriesFragment.kt) = FINE

[HomeFragment](https://github.com/DATL4G/BurningSeries-Android/blob/master/app/src/main/java/de/datlag/burningseries/ui/fragment/HomeFragment.kt#L127) -> [SeriesFragment](https://github.com/DATL4G/BurningSeries-Android/blob/master/app/src/main/java/de/datlag/burningseries/ui/fragment/SeriesFragment.kt) -> [VideoFragment](https://github.com/DATL4G/BurningSeries-Android/blob/master/app/src/main/java/de/datlag/burningseries/ui/fragment/VideoFragment.kt) -> [StreamUnavailableDialog](https://github.com/DATL4G/BurningSeries-Android/blob/master/app/src/main/java/de/datlag/burningseries/ui/dialog/StreamUnavailableDialog.kt) -> [ScrapeHosterFragment](https://github.com/DATL4G/BurningSeries-Android/blob/master/app/src/main/java/de/datlag/burningseries/ui/fragment/ScrapeHosterFragment.kt) -> [SaveScrapedDialog](https://github.com/DATL4G/BurningSeries-Android/blob/master/app/src/main/java/de/datlag/burningseries/ui/dialog/SaveScrapedDialog.kt) -> [SeriesFragment](https://github.com/DATL4G/BurningSeries-Android/blob/master/app/src/main/java/de/datlag/burningseries/ui/fragment/SeriesFragment.kt) = ERROR

All navigations are done using the [NavigationComponent](https://developer.android.com/guide/navigation/) with SafeArgs.
I'm accessing the views in the onViewCreated method.

**Comment by kirich1409** [comment]
You try to access in another thread (from Coroutine). I think View can be destroyed and that's why ViewBinding can't be created

**Comment by DATL4G** [comment]
Mhm no I don't think so. Or did I miss something?
I navigate back there in the [Main thread](https://github.com/DATL4G/BurningSeries-Android/blob/master/app/src/main/java/de/datlag/burningseries/ui/dialog/SaveScrapedDialog.kt#L51)

I start the flow collection in onViewCreated and do it the official recommended way
(This should collect the flow in main thread)
```kotlin
inline fun <T> Flow<T>.launchAndCollectIn(
    owner: LifecycleOwner,
    minActiveState: Lifecycle.State = Lifecycle.State.STARTED,
    crossinline action: suspend CoroutineScope.(T) -> Unit
) = owner.lifecycleScope.launch {
    owner.repeatOnLifecycle(minActiveState) {
        collect {
            action(it)
        }
    }
}
```
[Code snippet](https://github.com/DATL4G/BurningSeries-Android/blob/master/app/src/main/java/de/datlag/burningseries/ui/fragment/SeriesFragment.kt#L79)
```kotlin
navArgs.seriesWithInfo?.let { series ->
    setViewData(series)
    burningSeriesViewModel.getSeriesData(series.series.href, series.series.hrefTitle).launchAndCollect {
        seriesFlowCollect(it)
    }
}
```

And the navigation from HomeFragment works (but uses another navArg)

**Comment by kirich1409** [comment]
I am working on release with better error description that will help easier understand the reason

**Comment by DATL4G** [comment]
Nice. I look forward to it

**Comment by kirich1409** [comment]
Version 1.5.4 must be available in few hours

**Comment by DATL4G** [comment]
I cannot resolve Version 1.5.4 although the README displays version 1.5.4 (badge) and https://mvnrepository.com/artifact/com.github.kirich1409/viewbindingpropertydelegate/1.5.4 exists. Can you check that?

I already tried **Invalidate and Restart** in Android Studio as well as **Refresh Dependencies** using the Gradle tab in Android Studio.

Gradle Sync output:
```bash
Failed to resolve: viewbindingpropertydelegate-1.5.4
Affected Modules: app
```
Gradle implementation:
```gradle
implementation("com.github.kirich1409:viewbindingpropertydelegate:1.5.4")
```

**Comment by kirich1409** [comment]
I've checked and has no any issues. Try to remove Gradle cache in $HOME/.gradle/caches and try again to build your project

**Comment by DATL4G** [comment]
Just deleted the folder, opened the project and downloaded everything.
Still said it cannot resolve the dependency (1.5.3 however can), tried to build anyway

```bash
FAILURE: Build completed with 8 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Failed to transform viewbindingpropertydelegate-1.5.4.aar (com.github.kirich1409:viewbindingpropertydelegate:1.5.4) to match attributes {artifactType=android-databinding, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find viewbindingpropertydelegate-1.5.4.aar (com.github.kirich1409:viewbindingpropertydelegate:1.5.4).
        Searched in the following locations:
            https://repo.maven.apache.org/maven2/com/github/kirich1409/viewbindingpropertydelegate/1.5.4/viewbindingpropertydelegate-1.5.4.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
```

Other 7 errors are the same but other task names

**Comment by DATL4G** [comment]
There is no aar file, only jars and checksums etc https://repo.maven.apache.org/maven2/com/github/kirich1409/viewbindingpropertydelegate/1.5.4/

**Comment by kirich1409** [comment]
I've published 1.5.5 few minutes ago

**Comment by DATL4G** [comment]
Resolving 1.5.5 works however the is a duplicate class issue which prevents the app from building.
(Building still works fine when I switch back to 1.5.3, already checked my dependency tree)

```bash
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class by.kirich1409.viewbindingdelegate.ViewBindingPropertyDelegateKt found in modules jetified-viewbindingpropertydelegate-1.5.5-runtime (com.github.kirich1409:viewbindingpropertydelegate:1.5.5) and jetified-viewbindingpropertydelegate-noreflection-1.5.5-runtime (com.github.kirich1409:viewbindingpropertydelegate-noreflection:1.5.5)
     Duplicate class by.kirich1409.viewbindingdelegate.ViewBindingPropertyDelegateKt$viewBindingWithLifecycle$1 found in modules jetified-viewbindingpropertydelegate-1.5.5-runtime (com.github.kirich1409:viewbindingpropertydelegate:1.5.5) and jetified-viewbindingpropertydelegate-noreflection-1.5.5-runtime (com.github.kirich1409:viewbindingpropertydelegate-noreflection:1.5.5)
     Duplicate class by.kirich1409.viewbindingdelegate.ViewBindingPropertyDelegateKt$viewBindingWithLifecycle$2 found in modules jetified-viewbindingpropertydelegate-1.5.5-runtime (com.github.kirich1409:viewbindingpropertydelegate:1.5.5) and jetified-viewbindingpropertydelegate-noreflection-1.5.5-runtime (com.github.kirich1409:viewbindingpropertydelegate-noreflection:1.5.5)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by DATL4G** [comment]
Switched to the ```noreflection``` variant for now.
This builds fine

**Comment by DATL4G** [comment]
Back to the original issue:

The log shows
```bash
2022-01-05 22:25:46.868 16285-4024/de.datlag.burningseries E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: de.datlag.burningseries, PID: 16285
    java.lang.IllegalStateException: Fragment's view can't be accessed. Fragment isn't added
        at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:87)
        at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:63)
        at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:52)
        at de.datlag.burningseries.ui.fragment.ScrapeHosterFragment.getBinding(ScrapeHosterFragment.kt:34)
        at de.datlag.burningseries.ui.fragment.ScrapeHosterFragment.access$getBinding(ScrapeHosterFragment.kt:29)
        at de.datlag.burningseries.ui.fragment.ScrapeHosterFragment$saveStream$1$1.invokeSuspend(ScrapeHosterFragment.kt:92)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8030)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

It says that it cannot access the ScrapeHosterFragment well because thats true, the fragment I navigated to is SeriesFragment not ScrapeHosterFragment

That's the snippet where I navigate back and triggers this issue
```kotlin
binding.backButton.setOnClickListener {
    findNavController().navigate(SaveScrapedDialogDirections.actionSaveScrapedDialogToSeriesFragment(seriesWithInfo = navArgs.seriesWithInfo))
}
```

**Comment by kirich1409** [comment]
View isn't ready and how you want to create instance of ViewBinding?

**Comment by DATL4G** [comment]
If you want to look at any fragment it's here https://github.com/DATL4G/BurningSeries-Android/tree/master/app/src/main/java/de/datlag/burningseries/ui/fragment

Basically I do everything the same in fragments:

#### SeriesFragment
I navigate from SeriesFragment to ScrapeHosterFragment
```kotlin
class SeriesFragment : AdvancedFragment(R.layout.fragment_series) {
    private val binding: FragmentSeriesBinding by viewBinding()

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        // Access the views here using binding.view.setOnClickListener { /* for example */ }
    }
}
```

#### ScrapeHosterFragment
I navigate from ScrapeHosterFragment to SaveScrapedDialog
```kotlin
class ScrapeHosterFragment : AdvancedFragment(R.layout.fragment_scrape_hoster) {
    private val binding: FragmentScrapeHosterBinding by viewBinding()

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        // Access the views here
    }
}
```

#### SaveScrapedDialog
Navigation explained in comment
```kotlin
class SaveScrapedDialog : BottomSheetDialogFragment() {
    private val binding: DialogSaveScrapedBinding by viewBinding()

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        if (safeContext.packageManager.isTelevision()) {
            dialog?.setOnShowListener {
                it.expand()
            }
        }

        return inflater.inflate(R.layout.dialog_save_scraped, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        binding.continueButton.setOnClickListener {
            dismiss()
        }
        // I navigate here from SaveScrapedDialog to SeriesFragment and it causes the issue on the ScrapeHosterFragment
        binding.backButton.setOnClickListener {
            findNavController().navigate(SaveScrapedDialogDirections.actionSaveScrapedDialogToSeriesFragment(seriesWithInfo = navArgs.seriesWithInfo))
        }
    }
}
```

**Comment by kirich1409** [comment]
You execute Coroutine in `saveStream()` on background thread, and it has no guarantee to be executed when Fragment is attached or not destroyed. Before call UI check that
```kotlin
 private fun saveStream() = lifecycleScope.launch(Dispatchers.IO) {
        val scrapeJsInput = safeContext.resources.openRawResource(R.raw.scrape_hoster)
        val jsText = String(scrapeJsInput.readBytes())
        while (true) {
            if (getView() != null) {
               withContext(Dispatchers.Main) {
                   binding.webView.evaluateJavascript(jsText) {
                       if (it != null && it.isNotEmpty() && !it.equals("null", true)) {
                           saveScrapedData(it)
                       } 
                   }
               }
               delay(3000)
            } else {
               // Do something when view has been destroyed
            }
        }
    }
```

**Comment by kirich1409** [comment]
Or you can run coroutine attached to viewLifecycle. Read more about that [here](https://developer.android.com/reference/kotlin/androidx/lifecycle/package-summary#repeatonlifecycle).
