### ISSUE TITLE
  java.lang.IllegalStateException: Host view isn't ready to create a ViewBinding instance

### ISSUE THREAD

**Issue by xaldarof** [androidbroadcast/ViewBindingPropertyDelegate#96]
https://gist.github.com/xaldarof/09cf823f1e22a8b45cb52480f42eb85e

**Comment by davidgerka** [comment]
**hey,i find the error,can you fix it，thanks**

![1](https://user-images.githubusercontent.com/13624423/154619320-b9afbcbe-3d3e-4813-9fc0-f72fc0f64463.png)
![2](https://user-images.githubusercontent.com/13624423/154619335-6d213c63-2954-4cd5-96be-f65924f4a861.png)

**Comment by kirich1409** [comment]
I've tried to reproduce with the latest version (1.5.6). Everything work as expected. Did you use the latest version?
