### ISSUE TITLE
Lint errors when updated to 1.5.6

### ISSUE THREAD

**Issue by shalva97** [androidbroadcast/ViewBindingPropertyDelegate#97]
This is probably not related to the project, but for some reason when I add version 1.5.6 to my project it brings in another dependency `androidx.fragment:fragment:1.4.0@aar`, which causes lint errors:

```
/Users/george/.gradle/caches/transforms-3/a47ef7f3ecba251253213faaba0ec99a/transformed/fragment-1.4.0/jars/lint.jar: Error: Lint found an issue registry (androidx.fragment.lint.FragmentIssueRegistry) which requires a newer API level. That means that the custom lint checks are intended for a newer lint version; please upgrade. [ObsoleteLintCustomCheck]
```

This is mostly a problem on my project, but still.... I wonder why `androidx.fragment:fragment:1.4.0` is being added? I have looked at your library and it does not have dependency on that version at all. It  also does not show up in `external libraries` list on `Projec View`. But if I create a new project, add this library to it, out of nowhere `androidx.fragment:fragment:1.4.0` dependency is added, why version 1.4.0 and not 1.3.6, which is the dependency version written in the library?

**Comment by kirich1409** [comment]
You can use Gradle API to force version of any dependencies that you want. You can read about that [here](https://docs.gradle.org/current/userguide/resolution_rules.html)
